server:
  port: 8080
  servlet:
    session:
      timeout: 15m

spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.username: root
spring.datasource.url: jdbc:mysql://root@localhost:3306/cars
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.datasource.initialization-mode: always